management:
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST,PUT,OPTIONS,DELETE
        allowed-origins: '"*"'
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      livenessState:
        enabled: true
      readinessState:
        enabled: true
  info:
    env:
      enabled: true

spring:
  application:
    name: InfernoCTF
  datasource:
    url: jdbc:postgresql://${DB_IP:localhost}:${DB_PORT:5432}/${DB_NAME:infernoctf}
    username: ${DB_USER:amaterasu}
    password: ${DB_PASS:amaterasu}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  forward-headers-strategy: native
  port: ${PORT:8081}
  servlet:
    contextPath: /infernoctf-rest
  shutdown: graceful
  tomcat:
    internal-proxies:
      protocol-header: "X-Forwarded-Proto"
      remote-ip-header: "X-FORWARDED-FOR"
  use-forward-headers: true

infernoctf:
  applicationName: InfernoCTF
  defaultAdminUsername: infernoctf_admin
  defaultAdminPassword: password
  chatService: ""
  chatSocket: ""

logging:
  level:
    org.hibernate: WARN
    org.hibernate.orm.connections.pooling: ERROR
